[gcp_service_account]
type = "service_account"
project_id = "truck-tower"
private_key_id = "de30e6f700af4ed44fab259d629dda0027590271"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDH6Gffo7p3JVkZ
wFGnrijEn650Kkq4T2mVy7ncuWwWckvYcRhJxgivI4vd2uAYBuGHWa7OS96p5Nip
8nz9aH4GdwCw4h4vVHM8zq76iThfrQdVTATPwGic6g6z0Uk8FUg8vWSlJqiBhr2q
rheDH/huXm+k7N4daiKOuWOvzff/IUXVIaNjJNsvXRRi4RQ7casZxv0238TZXmie
1boXK3cElh5nUmURqUJf9SPwIRUFASjY9c+ovu8N7/vmDbveooqRpqDW4FyYAIX+
5StC6I776Lo248Ck4dC+2Rtp/KPuDcNRivh86H/eUwdUO0PsbpsCAWLJFFlCPPl7
8yQJB4LzAgMBAAECggEAGDtLnAg0qgyU6FIvk6vAtVTFyL73n6/AlK/FL8QqHe5s
0yeiUg73LoOYiKPnVgI/hDCSx97adq2Otcr266Cm5hG2u7os/n+2GEDVZPkNJEvM
/8HfM2+XPq4AajuMLQRHZVVvxbUR5+F1TCMeJn7Rlk9MKSmtItOirLo8IytMTFh9
TjmidBtSULztXc9CO1TnccPOR5uJGMdHT4W78KwJyHmyO1eN3Xnx891iavnLcJkZ
XqkxEmOInlK6Bjwbf7SkPMcMR6YXTNdQFx+LOOYg0ALKvZiyPKQT5WTWWpVfTHL8
qQZKmxEMZ00KO5GTclaagRJFTiSRNYURRAIV3cjiwQKBgQDj3+2N9VDbQenClxjN
663elRT0NyMtQE6H0+yUUZISj5NWRXym7bRQIxFUfQ3wsjq0tEB//nD/zZ418p1c
B7S+s5bTJ+BPwq6moOWq5p4PgSx/oLXmfwj9mFHJI91OveeFnE9DvqwHJYZd4qPw
g+a3sYoHQ1Vf/Zol1N8tmAHTFwKBgQDglNGUmXgDqe4YeabCO20WSxmr0k34pras
wTWam9XlusOISsSwUJApvIZIWSiXOiMzLzIY5TF6qelZ5lnjtnDkUCnOwb5YBIry
PMDHgBUTxu3lf6OsmivSEmVtnq/mh/yy4TkC0GwuuH7BZmH98ufknSNdklFteIKj
7JPF+njohQKBgAsr9kyIY19setZka/3keRC5hF54uYvFZFQ6apXW7e9lBJctLvBM
JRPstDPNMbrEMiab07Gyur1/yirg6yAQ7KaQzWsqwE+IvuFCcCAR0Fv4PENBkMlt
Hva32gKfdIEgxFIDmMs8dNig2VaO/vSSsuP8m0TB41SibUU/i3WDx0sfAoGAP7z8
3lfQH/oSgQ/FrEqBY1pdJs7BIljub4lGVWL1CgY/iGbv+7phr/a5hb8ILiNp6hTy
+u3RZSbj+4fM6zvUPngh5XRHOWPQq39ilzxavwouanwXT91RooVmE/59ncfqiDoz
nADbM0dZcjpEhXZzKgcPCneEdLVHHo7+QaoctqECgYEAnKwT63etBV0P5V6OjswH
o0lXJV+1nHDuX3Hk7SmqRQ+7sSJsK1TBybeqJwW2WJpPMapJC/rP7LNbS71MIYuH
n+DoLOP6HfOFdIbSzxMrXUT5xwbksv67TWI04l5bsx4wTDkDkjV+UdHhlCqgWl/5
pR2qwkWbg02rSZY1n0ZuGhA=
-----END PRIVATE KEY-----
"""
client_email = "truck-tower@truck-tower.iam.gserviceaccount.com"
client_id = "107150628644767987473"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/truck-tower%40truck-tower.iam.gserviceaccount.com"
